### ISSUE TITLE
Contributing page to replace GitHub link

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#1]
The GitHub repo link, while important, does not make sense in the website's navigation menu as it is an external link. Two solutions:

1. Append "GitHub" with an external link icon (ex. [`external-link-alt`](https://fontawesome.com/icons/external-link-alt))
2. Create a **Contributing** page (serratus.io/contributing) that includes GitHub link and more

Example:
---

Serratus is an Open-Science project [hosted on GitHub](https://github.com/ababaian/serratus). Our aim is to create a 100% reproducible study with 100% transparent and freely available data.

_We welcome all scientists and developers to contribute._

### Tools used

- git
- Vue.js
- aws-cli
- bowtie2
- ...

### Get in touch!

-  Join our [Slack channel](https://join.slack.com/t/hackseq-rna/shared_invite/zt-dwdg5uw0-TTcfrFagariqKpOSU_d6wg) on `hackseq-rna`: `/join #serratus`
- Take on an [open task on GitHub](https://github.com/ababaian/serratus/issues)

**Comment by ababaian** [comment]
Related: how much of the CONTRIBUTING.md in the repo is not in the wiki?

If that's cleaned up then we can reduce the CONTRIBUTING.md to the essentials on how to contribute. This can then form the basis for the website page on Contributing.
