### ISSUE TITLE
Low-number miscounting on the web-interface graphs

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#101]
There is one small anomaly I've noticed. When you query for a very specific set of viruses, the family-graph shows multiple libraries being present (two here) but the query returns only a sub-set (or none in some cases).
See: [Suniviridae](https://dev-summary2.serratus.io/explorer?family=Sunviridae&identity=%5B75-100%5D&coverage=%5B28-62%5D#result)

![Screenshot from 2021-02-10 10-51-46](https://user-images.githubusercontent.com/9220907/107557077-02b6e200-6b8e-11eb-8303-49c8d41467b9.png)

**Comment by victorlin** [comment]
The family graph is currently sourcing data from this file: [SerratusIO_scoreID.json](https://github.com/serratus-bio/serratus.io/tree/236ece71ca515dbe4d10a46d3199465209155d79/src/components/Explorer/data/SerratusIO_scoreID.json).

On `prod` branch (not updated with summary2), it is showing matching results: [Suniviridae](https://serratus.io/explorer?family=Sunviridae&identity=%5B75-100%5D&coverage=%5B28-62%5D#result)

Looks like it needs to be updated for the `summary2` data. Do you have a new version handy?

**Comment by victorlin** [comment]
Related, not sure if we need to update this file as well: [cov3ma.genbank.json](https://github.com/serratus-bio/serratus.io/blob/236ece71ca515dbe4d10a46d3199465209155d79/src/components/Explorer/data/cov3ma.genbank.json)

**Comment by ababaian** [comment]
right... we'll need to update that bad boy in `R` once that side of things are online. Let's swing back to this

**Comment by ababaian** [comment]
We do actually re-calculate score using an improved function in summary2, so this explains the discrepancy

**Comment by victorlin** [comment]
Actually, this data can be directly fetched with SQL:

```sql
select score, percent_identity, count(*)
from nfamily
where family_name = 'Sunviridae'
group by score, percent_identity
```
_execution time: 50ms_

Of course, this takes a lot longer to execute for large families (e.g. Coronaviridae ~20 seconds) since there are so many rows to scan. But it's a one-time execution that will be cached by the API. Plus, this allows flexibility to include the chart for other tables (genbank, phylum, protein, etc.) in the future.
