### ISSUE TITLE
Inconsistent naming between database and website

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#107]
There's a small mismatch between the new database and website routes in how they reference SRA run IDs.

- Database: `sra_id` is the SRA run ID column across all tables. @ababaian this is from your SQL schema spreadsheet.
- Website: `run` is used in query URLs (e.g. https://serratus.io/explorer?run=ERR2756788). This is from previous discussion at https://github.com/serratus-bio/serratus-db/issues/2#issuecomment-666345859.

We should pick one and be consistent. There are references to `serratus.io/explorer?run=` in the rebuttal so I want to get this ironed out.

Opinion with example: take an official route https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR2756788. This is logical because it's scoped to `sra`+`run`. For Serratus, I think it's reasonable to assume scope of SRA when using `run`. Having `/explorer?sra=ERR2756788` could prompt users to try `/explorer?sra=ERX2769781` which doesn't make sense. `/explorer?srarun=ERR2756788` could work too.

Also worth noting that database columns `family_name`/`genbank_id` are simply `family`/`genbank` in Serratus Explorer. Still different, but less of an annoyance to me.

**Comment by ababaian** [comment]
in the database it would be good to be more descriptive with what `run` is. I agree `sra_id` is the wrong name, we should go with `run_id`. I don't like the term `run` as it's ambiguous alone but it is the correct choice to use it.

**Comment by victorlin** [comment]
Yeah `run` is ambiguous but I suspect any database user should be familiar with Serratus being a SRA search tool, and if not then the column values should give it away. 2 tasks for me here:

1. update `sra_id` -> `run_id` for all tables in the database
2. add table column names+descriptions to https://github.com/ababaian/serratus/wiki/Serratus-SQL-Database-Management

This isn’t an issue for serratus.io anymore, but I’ll cross reference and close this once the tasks are done.

**Comment by victorlin** [comment]
Another thought: should database tables `nsra`/`psra`/`rsra` be renamed to `nrun`/`prun`/`rrun`?

**Comment by ababaian** [comment]
naw that database names are fine because it refers to the actual SRA as a whole
