### ISSUE TITLE
Update Serratus project theme

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#109]
Per paper revisions, website content should be modified to a less coronavirus-centric message.

### 1. Meta tags

https://www.opengraph.xyz/url/https:%2F%2Fserratus.io/

How about:

> Serratus is a collaborative Open Science project for ultra-rapid discovery of known and unknown viruses in public genomic sequence data.

### 2. About page

https://serratus.io/about - many references to coronavirus. We can probably pull some text from the paper to update this page.

**Comment by ababaian** [comment]
:+1: I will get on this

**Comment by victorlin** [comment]
I just remembered we have these index pages on the wiki: [[index] About](https://github.com/serratus-bio/serratus.io/wiki/%5Bindex%5D-About). So just edit there and let me know when you do :)

**Comment by ababaian** [comment]
perfect :+1:

**Comment by ababaian** [comment]
Updated the About Page.

**Comment by ababaian** [comment]
> Serratus: An open-science collaboration to uncover Earth's viruses
