### ISSUE TITLE
Current JBrowse implementation prevents nested routes

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#127]
Been trying to make `/explorer/rdrp` work, but keep running into this error:

![nested-route-jbrowse](https://user-images.githubusercontent.com/13424970/112736630-9c620500-8f2a-11eb-8e79-7d911089f166.png)

Note that `http://localhost:3000/explorer/dist/0.bundle.js` should be `http://localhost:3000/dist/0.bundle.js`.

This might be because we have compiled JBrowse files in our source (reason: https://github.com/serratus-bio/serratus.io/pull/77#discussion_r472482617). We can observe it building the path to `*.bundle.js` relative to the current path:

```
return i.p+""+({}[t]||t)+".bundle.js"
```

I've tried using `createBrowserHistory({ basename: '/' })` and removing `exact` from the `Route`, but no luck.

Reference:

- https://stackoverflow.com/questions/50275901/react-routing-path-not-working-bundle-not-found

**Comment by ababaian** [comment]
The RdRP will not work with JBrowse we don't have bam files. This is a nucleotide feature only.

**Comment by victorlin** [comment]
right, but

1. the JBrowse files are loaded with every page
2. we want to use `/explorer/nt`
