### ISSUE TITLE
 RdRp Geo map - Timeline

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#220]
The beta page for RdRp Geo Map (https://serratus.io/geo) with code components in https://github.com/serratus-bio/serratus.io/tree/main/src/components/Geo is a bit spartan.

The underlying data which the MapPlot.tsx function plots is stored in rdrp_pos.tsv and you can see the columns available here:

un_id	biosample_id	release_date	tax_id	scientific_name	coordinate_x	coordinate_y	from_text
DRR021448	SAMD00018415	2015-07-14 10:38:15	"318829"	Pyricularia oryzae	-53.073466889	-10.769946429	brazil
DRR022241	SAMD00018962	2015-02-17 09:27:39	"565456"	Thujopsis dolabrata var. hondae	140.74741987	40.82222627	japan:aomori
DRR022329	SAMD00019235	2018-01-09 20:09:36	"941566"	Enkianthus perulatus	134.22217792	35.49441833	japan: tottori
DRR022330	SAMD00019235	2018-01-09 20:09:37	"941566"	Enkianthus perulatus	134.22217792	35.49441833	japan: tottori
DRR023219	SAMD00019539	2014-12-04 10:09:40	"79674"	Macrobrachium rosenbergii	85.85766	20.18689	india: odisha, bhubaneswar, central institute of freshwater aquaculture
DRR023776	SAMD00020837	2015-02-14 09:39:34	"458240"	Arum concinnatum	25.14238	35.34194	greece: crete island
DRR024737	SAMD00022880	2015-11-24 10:21:11	"6161"	Dugesia japonica	137.04074133	35.752191505	japan:gifu, gujo, iruma river
DRR024738	SAMD00022878	2015-11-24 10:21:11	"6161"	Dugesia japonica	137.04074133	35.752191505	japan:gifu, gujo, iruma river
DRR029067	SAMD00024755	2015-01-26 10:28:37	"64793"	Wasmannia auropunctata	-52.97901	5.067	
DRR029069	SAMD00024757	2015-01-26 10:28:36	"64793"	Wasmannia auropunctata	-52.97901	5.067	
...

Task 2:

Create a `TimelinePlot.tsx` which is a bargraph which reads the actively  selected points in `MapPlot.tsx` (or if nothing is selected, display all points), and draws a timeline histogram for how many data points exist for each Month. The X-axis should remain static and encompass the total timeline of datapoints available, while the Y-axis should be dynamic and scale to the maximum height of points selected.

This is an example taken from the `palmID` codebase which was made in R.
![Screenshot from 2023-01-18 13-11-48](https://user-images.githubusercontent.com/9220907/213261489-c19cca36-128e-4a84-bba3-8494b88f2ef8.png)

**Comment by khanzardar** [comment]
I'll be working on this issue.

**Comment by lukepereira** [comment]
I'll work on cleaning up the previous PRs and getting them merged/deployed in main
