### ISSUE TITLE
JBrowse Integration

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#25]
@taltman @victorlin @lohrd 

### Implementation 1: Browse all 3.84 million virus alignments

We have ~14 TB of virus alignment data that's more or less locked up in some BAM file right now. Current analysis steps are 1. download bam file 2. load it into IGV 3. manually look-up the sequence accession in IGV to view the alignments.

We can radically simplify and open this data up if we implement [JBrowse](https://jbrowse.org) for this data.

### Implementation 2: Browse ~55,000 Coronavirus assemblies

For the deep dive on Cornaviruses we've assembled about 55,000 libraries into contigs, and if we identified a CoV-containing contig, the original reads from that library were re-aligned to both 1) The closest known Reference CoV genome and 2) The CoV-containing fragment itself.

In addition every CoV-contig has been processed by VADR so that it is annotated and we have domains/genes built into it.

To inspect and explore these novel CoV sequences we can run JBrowse on each of these references and serve the annotation/alignment data for it. This means that for all the ~55K assemblies we've done, we can instantly view it and help curate it.

----- 

For now let's focus on Implementation 2 which we have access to the data more immediatly, and we can swing back to Implementation 1 once all the 3.84 million files have been indexed which may take a week or more.

This issue supercedes #8

**Comment by victorlin** [comment]
looks like the authors of JBrowse are actively doing something with create-react-app: https://www.npmjs.com/package/@gmod/jbrowse-web

**Comment by ababaian** [comment]
Might be worth reaching out to them @victorlin and seeing if we can coordinate dev here so your work is more generalizable

**Comment by victorlin** [comment]
some static files to bootstrap bootstrap JBrowse integration efforts:

- https://s3.amazonaws.com/serratus-public/tmp/web/ERR2756788.bam
- https://s3.amazonaws.com/serratus-public/tmp/web/ERR2756788.sort.bam
- https://s3.amazonaws.com/serratus-public/tmp/web/ERR2756788.sort.bam.bai
- https://s3.amazonaws.com/serratus-public/tmp/web/cov3ma.fa
- https://s3.amazonaws.com/serratus-public/tmp/web/cov3ma.fa.fai
- https://s3.amazonaws.com/serratus-public/tmp/web/cov3ma.mask.bed

**Comment by cmdcolin** [comment]
Just posting if theres any questions let me know. The @gmod/jbrowse-web npm package is non functional right now, but is our work in progress jbrowse 2 release. Docs for jbrowse 2 are starting to come together at http://jbrowse.org/jb2/.

We have a tutorial here for embedding jbrowse 2 http://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_introduction but it is in beta state and doesn't have npm installable niceness just yet still working on packaging.

@lohrd reached out on github and this seems very interesting so happy to help in any way we can :+1:  he found some approaches for using jbrowse 1 and I'd be happy to assist if interested

Note there is also igv.js, it is nice and npm installable and a pretty good system https://github.com/igvteam/igv.js/ I think they do good work so happy to recommend them :)

**Comment by lohrd** [comment]
Oh wow, thanks for that, really appreciate the help and support. I am going to look into the JBrowse 2 tutorial now!

**Comment by victorlin** [comment]
@cmdcolin hey! Swinging back to this since we have a bug (#127) that could be solved by offloading the JBrowse files from our source. I noticed you've made some good progress on JBrowse 2 – any pointers on hooking it up to our current config?

https://github.com/serratus-bio/serratus.io/blob/f4152c225b888e83bec9d9158d3aa6749feffde5/src/pages/Jbrowse.jsx#L7-L29

**Comment by cmdcolin** [comment]
Interesting...you can try our package @jbrowse/react-linear-genome-view on npm, the readme for it should be an ok starter and we have a storybook here https://jbrowse.org/storybook/lgv/v1.3.0/

If you need any help lemme know ..
