### ISSUE TITLE
Paginate query results

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#34]
Currently, we are only displaying top 20 results from a `family`/`genbank` query, sorted by `score`/`cvgPct`. We should allow users to browse all results. This would require some work, but full data access is important.

Potential tasks:

1. update DB endpoint to slice data (ex. take top 0-10, 10-20, 20-30, ...)
2. update React component to display paginator and call DB accordingly

With this model, there is no extra work to be done on the D3 visualization side.

**Comment by lohrd** [comment]
DB endpoint for Accessions up and running: http://serratustest-dev-sumdb.us-east-1.elasticbeanstalk.com/api/runs/get-runs/NC_032111.1?page=2 

More to come!

**Comment by lohrd** [comment]
See PR#55
