### ISSUE TITLE
Query for unprocessed accession stays in Loading state

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#35]
Example: https://dev.serratus.io/query?run=SRR10980630

Interestingly, we also get a CORS error in the console for this:

> Access to XMLHttpRequest at 'https://db.serratus.io/api/runs/get-run/SRR10980630' from origin 'https://dev.serratus.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ababaian** [comment]
This file does not exist? 
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>bam/SRR10980630.bam</Key>
<RequestId>C8505A19898900AA</RequestId>
<HostId>
Faywt2rrs9Kg58Zak/+Vx35Y6h4+TAyhT0qANhQB/in3FeXdp+yakAK1tH6in90b9gyGql7t+rs=
</HostId>
</Error>
```

**Comment by victorlin** [comment]
@ababaian is it supposed to exist?

**Comment by ababaian** [comment]
don't think so, might be in the 'did not catch' category for this run

**Comment by victorlin** [comment]
on a related note, we should probably disable the download button when no results can be retrieved.

**Comment by ababaian** [comment]
well for now it's a good sanity check right :P

**Comment by victorlin** [comment]
haha that's true, directly linking to the ground truth S3 bucket isn't harmful for dev mode. I'll keep it there!
