### ISSUE TITLE
Search for results from GenBank accessions with human-friendly text

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#44]
### Motivation

GenBank accessions are cryptic. A better usage experience would be to search for GenBank accessions given some search string (e.g. _bat coronavirus_)

### Potential solution

- Leverage Entrez API which returns a set of GenBank accessions given the search string (e.g. https://www.ncbi.nlm.nih.gov/nuccore/?term=bat+coronavirus)
- A subset of these accessions have been processed by _Serratus_. Return results for this set in some way.

**Comment by ababaian** [comment]
This is the master-list of what we included in search: `s3://serratus-public/seq/cov3ma/cov3ma.sumzer.tsv`

Essentially a way to make this list 'explorable' is the primary objective.

**Comment by victorlin** [comment]
@ababaian is the new GenBank dropdown sufficient for this? Or is a searchable table-formatted page still desirable?

There's also the potential feature of returning results for multiple accessions (discussed in [this Slack thread](https://hackseq-rna.slack.com/archives/C012H9SDQCA/p1599235501234500)). Just need to know if that's a useful feature.

**Comment by ababaian** [comment]
yeah I really like the current GenBank implementation. I'd say for now this is sufficient.

**Comment by victorlin** [comment]
cool, closing this out.
