### ISSUE TITLE
Add footer indicating developmental stage of website

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#56]
To a visitor, it's not obvious that the website is still under active development. A global footer component with something like the following would make things clear:

> This website is still under [active development](https://github.com/serratus-bio/serratus.io). If you have any issues or feedback, please [submit an issue on GitHub](https://github.com/serratus-bio/serratus.io/issues/new) or reach out to serratusbio@gmail.com. As an open-source project, serratus.io also welcomes any contributors.

**Comment by Bryan-Tam** [comment]
I'm interested in trying this issue if you would have me.

**Comment by victorlin** [comment]
@Bryan-Tam go for it!

**Comment by Bryan-Tam** [comment]
Would it be preferred if this footer is a component? I noticed your components either handle dynamic data (props) or contain multiple sub elements. As it only contains a static string with hyperlink, I simply put it into a footer element.

**Comment by victorlin** [comment]
@Bryan-Tam it should be functionally comparable to [`Navbar`](https://github.com/serratus-bio/serratus.io/blob/677f0dbc/src/components/Navbar.jsx). So it should go in a separate file like `src/components/Footer.jsx`.

For the hyperlinks, see if you can use the component [`src/helpers/common/ExternalLink`](https://github.com/serratus-bio/serratus.io/blob/677f0dbc/src/helpers/common.jsx). This is in place so we can change the behavior across all links in the future if needed.

**Comment by victorlin** [comment]
Also, there might be some wonkiness on the homepage since it's using `position: fixed`. If you run into that, feel free to just ignore rendering for that route:

```jsx
{location.pathname !== '' && <Footer />}
```
