### ISSUE TITLE
Missing mobile-friendly navigation

### ISSUE THREAD

**Issue by victorlin** [serratus-bio/serratus.io#64]
Currently, the website navigation isn't very mobile-friendly (only bidirectional access for home and query page). Some sort of hamburger menu would be nice.

Distribution of site visitors from preprint publicity yesterday:

<img width="306" alt="user-devices" src="https://user-images.githubusercontent.com/13424970/90039304-72f2b280-dc94-11ea-9a02-daed1f5192df.png">

~1 in 4 visitors used a mobile device

**Comment by ababaian** [comment]
Related to this we currently have many items in the top `navbar` if we can group them and add pull-down menus to navigate the site (with a short descriptor for each entry) this can make navigating easier.

- [x] Add reactive hamburger pulldown for mobile

- [ ] Add Drop-down menus for navbar
	- On 'hover'  fade-in animation of the menu (0.25s)

- [ ] Change "Wiki" button to helpIcon with `Wiki` text shown on hover

Proposed Navbar Organization (Title - Description)
```
Explorer	
	NT   - Nucleotide-level, intra-species index
	RdRP - Amino Acid-level, inter-species discovery

Tools
	Map (beta) - Geospatial mapping of viral RdRP
	palmID (beta) - Input RdRP Sequence Analysis
	Trees (beta) - Automated palmprint phylogenies
```

**Comment by binoyskumar92** [comment]
Working on it

**Comment by victorlin** [comment]
Thanks @binoyskumar92!
