### ISSUE TITLE
Pagination: Virological Feedback

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#75]
Some feedback from [Virological](https://virological.org/t/serratus-the-ultra-deep-search-to-discover-novel-coronaviruses/516/5)

> This is really cool! Since you asked for suggestions on making the data more explorable via the web interface, can I suggest:
> 
>     When viewing all the SRA runs with matching reads, add a ‘download summary’ button that allows you to download either a list of all matching SRA accessions.
> 
>     The first page of search results doesn’t indicate how the size of the result set. It simply says ‘Page 1 out of …’
> 
>     It might not be feasible, but if the number of bowtie2 mapped reads is calculated for each dataset, having a way to download those reads specifically through sratools for additional analysis would be incredibly useful.
> 
> Thanks!
> 
> dave

**Comment by ababaian** [comment]
1. and 3. are already solved.

The second point:

 " The first page of search results doesn’t indicate how the size of the result set. It simply says ‘Page 1 out of …""

Most likely with the higher traffic we're timing out of the SQL queries. I don't think the current query system is scalable so I propose a simple hack solution

1. Add a limit of 1000 pages when doing this query, so if it's >10000  entries returned then it just says "1000+" instead of "58,345") for pages. This will  cut down the query calculation time by quite abit.

2. If we want to be smart about it, for each 'standard' family search (i.e. all Coronaviridae, all Filoviridae), precalculate the number of entries returned and then the "pages" number can be reported as the full number "58,123" and it can be looked up directly in a very small table.

- Coronaviridae - 580,200 entries ==> 5,802 pages
- Filoviridae - 674,234 entries ==> 6,743 pages
- ...

**Comment by victorlin** [comment]
not a timeout issue - we just need to fix the call to get that number to have it load after page render. shouldn’t be difficult, other elements on the page are doing something similar.

right now we have it fixed at 20 items per page, and displaying the number of pages

**Comment by victorlin** [comment]
related issue: "next" button should be invisible on last page.

for queries with a result set n<20, it should just display "Page 1 of 1" with no buttons.

example: https://dev-query-filter.serratus.io/query?family=Coronaviridae&identity=%5B75-81%5D&coverage=%5B25-100%5D

**Comment by victorlin** [comment]
another related issue: “Page 1 of 0” for invalid queries. simple solution would be to not return the component when number of pages is 0.

example: https://dev-query-filter.serratus.io/query?genbank=invalid

**Comment by victorlin** [comment]
Yet another one (this is getting tricky):

1. go to https://serratus.io/query?run=ERR2756788
2. switch query type to "Family" or "GenBank"

Pagination shows when it's not supposed to.

Overall, there's many non-optimal approaches with the Query page - it's due for some refactoring. I'm adding some changes to #73, but will need to refactor other stuff separately.

**Comment by lohrd** [comment]
I have a fix in mind and totally agree with you on the refactor. 

I think the 'dataPromise' should be consumed on the parent 'Query' page and the state should be managed there, then passed down to the 'QueryResult' and 'Paginator' components. This way, the Query page has access to the data being passed into the 'QueryResult' and 'Paginator' components, which will make all of this conditional rendering much easier.

**Comment by victorlin** [comment]
Pagination issues fixed by #87 refactoring.
